name: unittest

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]


jobs:
  build:
    name: xorfilter
    runs-on: ubuntu-latest


    strategy:
      matrix:
        toolchain:
          - "stable"
          - "nightly"
        profile:
          - "--release"
          # Disable debug mode test
          # It's about 10 times slower with debug mode: ~ 10 minutes
          # - ""
        cmd:
          - "build"
          - "test"


    steps:
      - name: Install toolchain with clippy available
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ matrix.toolchain }}"
          override: true
          components: clippy


      - uses: actions/checkout@v1


      - name: "${{ matrix.toolchain }} ${{ matrix.cmd }} ${{ matrix.profile }}"
        uses: actions-rs/cargo@v1
        with:
          command: "${{ matrix.cmd }}"
          args: --verbose ${{ matrix.profile }}
